name: Docker

on:
  pull_request: {}
  push:
    branches:
      - master

    tags: []

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t pmaene/splashdown:latest .
          docker push pmaene/splashdown:latest
