name: Docker

on:
  pull_request: {}
  push:
    branches:
      - master

    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate metadata for Docker
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.8.1
        with:
          images: ghcr.io/${{ github.repository }}
          tag-match: v(.*)
          tag-match-group: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2.1.0
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
