name: Docker

on:
  pull_request: {}
  push:
    branches:
      - master

    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker
        uses: actions/cache@v2.1.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            ${{ runner.os }}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1.0.4

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Generate metadata for Docker
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: ghcr.io/${{ github.repository }}
          tag-match: v(.*)
          tag-match-group: 1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
